Vagrant.configure("2") do |config|
  # Vagrant box
  config.vm.box = "ubuntu/xenial64"

  # Provider
  config.vm.provider 'virtualbox' do |vb|
    vb.name = "Devagrant-Test"
    vb.memory = 1024
    vb.cpus = 2
  end

  $script = <<-SCRIPT
  git clone https://gitlab.com/cabaalexander/dot-files.git
  SCRIPT

  # Clone my dot-files repo and do the magic
  config.vm.provision "shell", inline: $script, privileged: false
end

