# vim: ft=ruby

Vagrant.configure("2") do |config|
  # Vagrant box
  config.vm.box = "archlinux/archlinux"

  # Provider
  config.vm.provider 'virtualbox' do |vb|
    vb.name = "DevagrantTest"
    vb.memory = 1024
    vb.cpus = 2
  end

  # Hostname
  config.vm.hostname = "DevagrantTest-HOST"

  # Host only network
  config.vm.network "public_network", :bridge => "wlan0"

  $script = <<-SCRIPT
  # Adding mirror list `Santo_Domingo` near(ish)
  sudo cp -f /vagrant/config/etc-pacman-d-mirrorlist /etc/pacman.d/mirrorlist

  echo "[Updating PKM]"
  sudo pacman --noconfirm -Syu &> /dev/null
  sudo pacman --noconfirm -S base-devel git vim &> /dev/null
  sudo ln -sf /usr/share/zoneinfo/America/Santo_Domingo /etc/localtime

  git clone https://github.com/cabaalexander/dot-files.git
  SCRIPT

  # Clone my dot-files repo and do the magic
  config.vm.provision "shell", inline: $script, privileged: false
end

