# vim: ft=ruby:ts=2:sw=2

Vagrant.configure("2") do |config|
  # Vagrant box
  config.vm.box = "archlinux/archlinux"

  # # Use this in case of no internet connection ¯\\_(ツ)_/¯
  # config.vm.provider :virtualbox do |vb|
  #   vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  # end

  config.vm.provider 'virtualbox' do |vb|
    vb.name = "DevagrantSandbox"
    vb.memory = 1024
    vb.cpus = 2
  end

  # Hostname
  config.vm.hostname = "DevagrantSandbox"

  # Host only network
  config.vm.network "public_network", bridge: [
    "en0: Wi-Fi (Wireless)",
  ]

  # Provisioning
  $script = <<-SCRIPT
  # Adding mirror list `Santo_Domingo` near(ish)
  sudo cp -f /vagrant/config/etc-pacman-d-mirrorlist /etc/pacman.d/mirrorlist

  echo "[Updating PKM]"
  sudo pacman --noconfirm -Syu
  sudo pacman --noconfirm -S base-devel git vim
  sudo ln -sf /usr/share/zoneinfo/America/Santo_Domingo /etc/localtime

  git clone https://github.com/cabaalexander/dotfiles.git
  SCRIPT

  # Install
  $install = <<-INSTALL
  cd dotfiles
  make && make install
  INSTALL

  # Clone my dotfiles repo and do the magic
  config.vm.provision "shell", inline: $script, privileged: false
  # # simulate full install
  # config.vm.provision "shell", env: {"PASSWORD" => "vagrant"}, inline: $install, privileged: false
end

