# Functions

grsh(){
  if [ -z "$1" ]; then
    echo "How many resets?"
    return
  fi
  git reset --hard HEAD~${1}
}

grss(){
  if [ -z "$1" ]; then
    echo "How many resets?"
    return
  fi
  git reset --soft HEAD~${1}
}

gsq(){
  if [ -z "$1" ]; then
    echo "How many commits do you wanna squash?"
    return
  fi
  git rebase -i HEAD~${1}
}

gpf(){
  read -p "Are you sure that you want to pull hard ? Really hard ? [y, n]: " is_hard
  if [ "$is_hard" == "y" ]
  then
    currentBranch=`git symbolic-ref --short -q HEAD` # `` to run commands
    git fetch -v origin ${currentBranch}
    git reset --hard origin/${currentBranch}
  fi
}

gprune(){
  # Actualizando los branches locales a como esta en remoto
  #git checkout master
  #git fetch
  #git fetch --prune

  # Lista de branches locales actualizados
  remoteBranches=`git branch -r | sed 's:  origin/::g'`


  # Lista de branches remotos actualizados
  localBranches=`git branch | cut -c 3-`

  for localBranch in $localBranches; do

    # Variable para saber si $localBranch se va a borrar
    delCurrentBranch=true

    for remoteB in $remoteBranches; do

      # Revisar si el branch local esta entre los remotos
      if [ $localBranch = $remoteB ]; then
        delCurrentBranch=false
      fi
    done # Final del for para remote branches

    # Solo sera true si el branch local NO esta entre los branches remotos
    if [ $delCurrentBranch = true ]; then
      git branch -D $localB
    fi

  done # Final del for para local branches
}

cddropbox(){
  if [ ! -z "$1" ]; then
    cd ~/Dropbox/mac/$1
  else
    cd ~/Dropbox/mac/ && l
  fi
}

aliases(){
  case $1 in
    "-e")
      nvim ~/.bash_aliases
      ;;
    "-a")
      if [ ! -z "$2" ] && [ ! -z "$3" ]; then
        echo "alias $2='$3'" >> ~/.bash_aliases
      else
        echo ":: Error :: Did not add the alias..."
        echo -e "Options:\n    [-e]\t\t    Edit\n    [-a] <name> <value>\t    Add\n    [-f] <PATTERN>\t    Find"
      fi
      ;;
    "-f")
      alias | grep "$2"
      ;;
    *)
      echo -e "Options:\n    [-e]\t\t    Edit\n    [-a] <name> <value>\t    Add\n    [-f] <PATTERN>\t    Find"
      ;;
  esac
}

lstree(){
  clear
	if [ -z "$1" ]; then
		tree -C
	else
		tree -CL $(($1+1))
	fi
}

# Git Aliases
alias gb='git branch'
alias gs='clear && git status'
alias ga='git add'
alias gall='git add -A && git status'
alias gl='git log'
alias gk='gitk'
alias gf='git fetch -v'
alias ggo='git checkout'
alias gd='clear && git diff'
alias gp='git fetch && git pull'
alias gpr='git fetch -v && git pull --rebase origin master'
alias gprup='git pull --rebase upstream master'
alias gdt='git difftool'
alias gdm='git diff remotes/origin/master..'
alias gmt='git mergetool'
alias grl='git reflog'
alias gst='git stash'
alias gcm='git commit'
alias grs='git reset'
alias gcl='git clone'
alias grb='git rebase'
alias grf='git show-ref'
alias gma='git merge --abort'
alias gcmm='git commit -m'
alias grbm='git rebase master'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'
alias gcma='git commit --amend'
alias gcman='git commit --amend --no-edit --no-verify'
alias gdms='git diff --stat --color master..'
alias gclean='git clean -df'
alias lsgst='git stash list'
alias uptrefs='git fetch origin --prune'
alias gr='git remote'

# Other Aliases
alias xx='exit'
alias ali='aliases'
alias editbash='nvim ~/.bashrc'
alias bgdisown='bg && disown'
alias poweroff='shutdown -P now'
alias lsnpm='npm ls --depth 0'
alias rnpm='npm remove'
alias lsgem='gem list'
alias rbow='bower uninstall'
alias lsbow='bower list'
alias rst='reset'
alias editvimconfig='nvim ~/.config/nvim/init.vim'
alias susu='sudo su'
alias nvmv='nvm current'
alias nvmd='nvm alias default '
alias delnpm='rm -rf ./node_modules'
alias rstnpm='clear && rm -rf ./node_modules && npm i && npm i'
alias delbuild='rm -rf ./build'
alias cdhttp='clear && cd /srv/http && ls'
alias ..='cd ..'
alias cdssh='cd ~/.ssh && ls'

# Docker
alias dki='docker images'
alias dkps='docker ps'
alias dk='dk'
alias dkinfo='dki && echo -e "\n\n#######################\n\n" && dkps -a'

# Elm
alias celm="./node_modules/.bin/elm"
alias celm-make="./node_modules/.bin/elm-make"
alias celm-package="./node_modules/.bin/elm-package"
alias celm-reactor="./node_modules/.bin/elm-reactor"
alias celm-repl="./node_modules/.bin/elm-repl"

# HAM
alias conto='gall && gcman && gps -f'

# Other Things
alias srbash='source ~/.bashrc'
alias ee='nvim'
alias npmprune='npm prune && npm i'
alias gdl='git log -p -1'
alias gfup='git fetch upstream'
alias del='rm -rf'
alias editbutils="nvim $HOME/.bash_utils"
alias lsnvm='nvm list'

# Tmux
alias tm='tmux'
alias tma='tmux attach'

# ls aliases
alias l='ls -CF --color=auto'
alias la='ls -A --color=auto'
alias ll='ls -lF --color=auto'
alias lla='ls -lFa --color=auto'

